# Embargo global settings
# These may all be overridden in a local project

# if false, does not initialize a new git repository on project creation
use_git = true

# only gcc is currently supported
toolchain = "gcc"

cxx_version = "c++17"

# Below are the default package paths
# These can all be overridden in the local Embargo.toml or changed in this file
# But regardless, these values still need to be set or else Embargo will not run

# Relative to Embargo.toml
source_path = "src"

# Relative to Embargo.toml
build_path = "target"

# Where the builds are saved, relative to build path above
target_path_debug = "debug"
target_path_release = "release"

# Where the .o files are saved, relative to target path
object_path = ".artifacts"

# Directory where the executable/library are saved, relative to target path
bin_path = "bin"
lib_path = "lib"
