# Embargo global settings
# These may all be overridden in a local project

# if false, does not initialize a new git repository on project creation
use_git = true

# only gcc is currently supported
toolchain = "gcc"

cxx_version = "c++17"

# Below are the default package paths
# These can all be overridden in the local Embargo.toml or changed in this file
# But regardless, these values still need to be set or else Embargo will not run

# Relative to Embargo.toml
source_path = "src"

# Relative to Embargo.toml
build_path = "build"

# Where the executable is saved, relative to build path
bin_path = "bin"

# Where the .o files are saved, relative to build path
object_path = "objects"